[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bio_utils"
version = "0.1.0"
description = "A Python package for DNA sequence analysis."
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/bio_utils"]